#!/bin/bash

help() {
echo "Weather, version 1.0"
echo "Usage:  weather [location]"
echo ""
echo Weather location options:
echo "  City, State"
echo "  City, ST"
echo "  Zip/Postal Code"
echo ""
echo "NOTES:"
echo "Currently only US Zip Codes and Canadian Postal Codes are recognized."
echo "In the future it may be possible to add other country postal codes."
}

get_weather() {
curl wttr.in/${LOCATION// /_}
}

get_zip() {
IP="$(curl -s ipinfo.io/ip)"
ZIP=$(curl -s ipinfo.io/$IP | awk -F ":" '/postal/ { print $2 }' | sed -e 's/^\ "//' -e 's/"$//')
}

get_city() {
CITY=$(curl -s ipinfo.io/$IP | awk -F ":" '/city/ { print $2 }' | sed -e 's/^\ "//' -e 's/",$//')
}

get_state() {
STATE=$(curl -s ipinfo.io/$IP | awk -F ":" '/region/ { print $2 }' | sed -e 's/^\ "//' -e 's/",$//')
}

get_location() {
LOCATION="$CITY, $STATE"
}

if [ "$1" == "-h" ]; then
        help
        exit
elif [ $# -eq 0 ]; then
        get_city
        get_state
        get_location
        echo "No city provided. Defaulting to $CITY, $STATE"
        echo $LOCATION
        get_weather
else
        LOCATION=$@
        get_weather
fi
